### ISSUE TITLE
Integration not loaded on HA 2023.11.1

### ISSUE THREAD

**Issue by T1nn13** [hardbyte/ha-evnex#17]
Seems like HA is looking for evnex version 0.3.5 but evnex is at 0.3.1 I believe.

Is this the right place to open the issue or should I open in in ha-core repo?

Logger: homeassistant.setup
Source: setup.py:185
First occurred: 09:10:49 (1 occurrences)
Last logged: 09:10:49

Setup failed for custom integration evnex: Requirements for evnex not found: ['evnex>=0.3.5'].

**Comment by sydney2711** [comment]
Hi
I had the same problem with core 11.0.
Went back to core 10.5 and everything works again.
Hope there is an easy fix.

Cheers

**Comment by xxxarmitagexx** [comment]
Having the same issue after updating to core 11.0.

Also hope there is a fix soon.

**Comment by hardbyte** [comment]
Thanks all - have just pushed a quick fix in v0.4. Let me know how that goes.

**Comment by T1nn13** [comment]
Thanks for having a look so quickly. I can confirm that the integration is not loading.
All the sensors are working also.

However, the control section is not functional. Charge now, connector availability switches are in error. Seems to be failing at the setup stage.

Logger: homeassistant.setup
Source: setup.py:359
First occurred: 21:37:20 (2 occurrences)
Last logged: 21:37:20

Unable to prepare setup for platform evnex.switch: Platform not found (cannot import name 'Evnex' from 'evnex' (/usr/local/lib/python3.11/site-packages/evnex/__init__.py)).
Unable to prepare setup for platform evnex.number: Platform not found (cannot import name 'Evnex' from 'evnex' (/usr/local/lib/python3.11/site-packages/evnex/__init__.py)).

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by drc38** [comment]
PR #18 will fix the above error

**Comment by T1nn13** [comment]
Perfect! In that case, we are all good. Thanks for the info and the help. Much appreciated.
