### ISSUE TITLE
Fails to load in HA 2024.1.0 due to 'evnex>=0.3.5'

### ISSUE THREAD

**Issue by sultanoswing** [hardbyte/ha-evnex#19]
A couple of errors in the logs today after updating to 2024.1.0, preventing the evnex integration from loading.

1. Logger: homeassistant.setup
Source: setup.py:221
First occurred: 07:44:24 (1 occurrences)
Last logged: 07:44:24

Setup failed for custom integration 'evnex': Requirements for evnex not found: ['evnex>=0.3.5'].

2. Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 07:44:20 (3 occurrences)
Last logged: 07:44:24

Unable to install package evnex>=0.3.5: ERROR: Cannot install evnex==0.3.5 and evnex==0.3.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by hardbyte** [comment]
I've updated my HA to 2024 and released a new version of ha-evnex that seems to work. That said my Python setup probably isn't standard so your mileage may vary! Please let me know if v 0.4.2 works for you

**Comment by drc38** [comment]
Hi Brian, the issue is with the httpx version specified:
![image](https://github.com/hardbyte/ha-evnex/assets/20024196/2e32d32d-1c3a-4503-9c0e-07c6e6d2454a)

**Comment by colinjgibbs** [comment]
Have upgrade HA to 2024.1.1 and evnex to 0.5. I now get this error:

Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 11:36:15 (3 occurrences)
Last logged: 11:36:30

Unable to install package evnex>=0.3.8: ERROR: Cannot install evnex==0.3.8 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by hardbyte** [comment]
I don't suppose you can see what conflicts? I'm guessing some other integration might depend on the old v1 version of `pydantic`?

**Comment by hardbyte** [comment]
Oh its a big issue with core plugins as well - https://github.com/home-assistant/core/issues/99218

Looks like I'll need to revert to using Pydantic v1 but support Pydantic v2.

**Comment by hardbyte** [comment]
🤞🏼 https://github.com/hardbyte/ha-evnex/releases/tag/v0.5.1

**Comment by sultanoswing** [comment]
Your fingers crossed emoji worked! All up & running again, thanks hardbyte / Brian.

**Comment by colinjgibbs** [comment]
Yup all working here as well. Thanks for the fast turnaround.
