### ISSUE TITLE
HA install and configuration

### ISSUE THREAD

**Issue by colinjgibbs** [hardbyte/ha-evnex#2]
Have installed via HACS and restarted. The integration shows in HACS but not in HA, and therefore there is nowhere to configure it (I assume it needs my Evnex account details etc).  
System info: 
Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest
HACS info:
Integration version: 1.27.2
Frontend version: | 20220906112053
Repositories: | 1119
Downloaded repositories: | 22

This is quite probably user error on my part but I can't figure out what else to do.

**Comment by axlback** [comment]
Have you added the integration from within HA (settings, integrations, add new)? Once you’ve installed the integration using HACS you still need to add it to HA.

**Comment by colinjgibbs** [comment]
That was the issue - it didn't show in HA integrations, when I went to add it.  But, I have now done a full power stop host and power cycle of the Pi, and now it shows up.  So I will close this issue - I assume it was something weird in my system - I had just restored from a backup so it may be something to do with that.

**Comment by colinjgibbs** [comment]
Have done a full stop host, power cycle and reboot and now the integration is showing up. Not sure what the problem was, but I had only just before installing the integration restored a full backup. I seem to recall something similar in the past.  Anyway, good news.

**Comment by colinjgibbs** [comment]
Have done a full stop host, power cycle and reboot and now the integration is showing up. Not sure what the problem was, but I had only just before installing the integration restored a full backup. I seem to recall something similar in the past. Anyway, good news.
