### ISSUE TITLE
Unhandled exception while updating evnex info

### ISSUE THREAD

**Issue by colinjgibbs** [hardbyte/ha-evnex#3]
After reboot of HA at hardware level, I added the integration and entered my evnex credentials which were accepted. The integration stayed in the "initialising" state for a minute or so, then errored with "Retrying setup".  The following message is from the logs:

_This error originated from a custom integration.

Logger: custom_components.evnex
Source: custom_components/evnex/__init__.py:200
Integration: Evnex EV Charger (documentation, issues)
First occurred: 16:10:27 (3 occurrences)
Last logged: 16:10:48

Unhandled exception while updating evnex info_

Here is my System info:
Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

Contents of manifest.json from custom_components/evnex:
{
  "domain": "evnex",
  "name": "Evnex EV Charger",
  "issue_tracker": "https://github.com/hardbyte/ha-evnex/issues",
  "config_flow": true,
  "version": "0.1.0",
  "documentation": "https://github.com/hardbyte/ha-evnex",
  "requirements": [
    "evnex==0.2.4"
  ],
  "codeowners": [
    "@hardbyte"
  ],
  "iot_class": "cloud_polling",
  "loggers": ["evnex"]
}

**Comment by hardbyte** [comment]
Hi @colinjgibbs thanks for the bug report. I believe you're the first user that isn't me.

Did you install via HACS or some other method? I ask because it looks like you haven't got the latest version (0.2.0 for ha-evnex and 0.2.9 for python-evnex). That could be because I need to do something after publishing a new release, or it could be because you installed from source?

**Comment by hardbyte** [comment]
I'm assuming you're using HACS and I found what I did wrong.

I'll create Github releases following the docs [here](https://hacs.xyz/docs/publish/integration/#github-releases-optional).

You should see an update asap

**Comment by colinjgibbs** [comment]
That's great. Yes I was using HACS

**Comment by colinjgibbs** [comment]
Well, I got the update and installed it via HACS, restarted HA.  On startup I now get:
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 18:13:08 (3 occurrences)
Last logged: 18:13:22

Unable to install package evnex==0.2.10: ERROR: Could not find a version that satisfies the requirement evnex==0.2.10 (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9) ERROR: No matching distribution found for evnex==0.2.10

I'm just wondering if its confusion between 0.2.1 and 0.2.10?  Here is the manifest file now:
{
  "domain": "evnex",
  "name": "Evnex EV Charger",
  "issue_tracker": "https://github.com/hardbyte/ha-evnex/issues",
  "config_flow": true,
  "version": "0.2.1",
  "documentation": "https://github.com/hardbyte/ha-evnex",
  "requirements": [
    "evnex==0.2.10"
  ],
  "codeowners": [
    "@hardbyte"
  ],
  "iot_class": "cloud_polling",
  "loggers": ["evnex"]
}

I tried uninstalling and re downloading but HA will not let me delete the integration (from the Devices->Intgerations page.  It  doesn't error, it just accepts the 'OK' and does nothing.  Happy to do further investigation, just tell me what you'd like me to do?

**Comment by hardbyte** [comment]
Okay that issue was easy enough, it should at least install with HACS now.

I've been running the custom integration directly but I'm going to switch to use HACS so I hopefully run into and fix the issues before making another release. I'm just trying to make a pre-release (you might see it in HACS) but I'll post here if it works for me from HACS.

**Comment by hardbyte** [comment]
Redownloading seems to work from the HACS page - top right:

![image](https://user-images.githubusercontent.com/855189/191695923-f4ee97ed-e0d2-4bfa-809d-36c9418c71f0.png)

Then you can pick the version:
![image](https://user-images.githubusercontent.com/855189/191695685-82e09031-27f7-4a28-97ce-2516178e765e.png)

**Comment by hardbyte** [comment]
Ok updating to that beta version then restarting home assistant I'm running the integration now under HACS. 

Would you mind updating to the beta and let me know if everything seems to be working? I'll try quieten the logs I didn't realize the debug messages would show up in a proper install.

**Comment by colinjgibbs** [comment]
Yup 2.2 works. See screen shot
![Screen Shot 2022-09-22 at 8 29 16 PM](https://user-images.githubusercontent.com/74024699/191698225-3b7b32be-6140-4507-8003-127422e68851.png)

**Comment by colinjgibbs** [comment]
Sorry just read your update - I'll update to the beta

**Comment by hardbyte** [comment]
Fantastic! No need to update if its working as I was just tweaking dependencies. 

I'll close this issue now but please open another with any problems or suggestions.
