### ISSUE TITLE
Api differences with Commercial org?

### ISSUE THREAD

**Issue by drc38** [hardbyte/ha-evnex#5]
In order to get the HA add-on to fully load I had to change the `org.id` to `org.slug` and comment out the override call (which was returning a NotFound error). 

Seems odd that a cloud api would behave differently, I am on firmware 1.2.7.4CFFD14. Any ideas?

**Comment by drc38** [comment]
Suggest including handling for this in the check api response:
`{"errors": [{"status": "404","title": "NotFoundError"}]}`

**Comment by hardbyte** [comment]
Thanks for the report, I'd very much like to ensure that the python lib and the HA integration work for commercial orgs too.

Would you be able to share a bit more detail - which schema did you need to alter? I did find issues with get override if the charge point was offline, I have hopefully protected against that with the latest version.

**Comment by drc38** [comment]
Looks like slug should be used based on the evnex web app:
`path={`/v2/apps/organisations/${orgSlug}/charge-points`}`
